# app.py

import streamlit as st
from src.rag_system import rag_query

st.title("Skyrim RAG System")

query = st.text_input("Enter your query about Skyrim characters:")

if query:
    with st.spinner("Generating response..."):
        response = rag_query(query)
    
    st.subheader("Response:")
    st.write(response)

    st.subheader("Example characters from the dataset:")
    st.write("1. Ragnar: Nord Male Miner with skills in Smithing and Two-handed [1](https://app.textcortex.com/file?id=file_01jmddrh97ffksrmyf8gthbmsy&state=eyJzbmlwcGV0IjoiJTJGd2lraSUyRlNreXJpbSUzQVJhZ25hciUyQ1JhZ25hciUyQ05vcmQlMkNNYWxlJTJDTWluZXIlMkM5MSUyQzY3JTJDNjclMkMlMjJTbWl0aGluZyUyQyUyMFR3by1oYW5kZWQlMjIlMkNDcmltZUZhY3Rpb25SZWFjaCUzQiUyMEpvYk1pbmVyRmFjdGlvbiUzQiUyMEthcnRod2FzdGVuTWluZXJzQmFycmFja3NGYWN0aW9uJTNCJTIwVG93bkthcnRod2FzdGVuRmFjdGlvbiUyQ05vJTJDVW5hZ2dyZXNzaXZlJTJDTm8lMjBDcmltZSUyQyUyQzIwJTJDMTUlMkMyMCUyQzI1JTJDMjAlMkMxNSUyQzIwJTJDMTUlMkMxNSUyQzE1JTJDMjAlMkMxNSUyQzE1JTJDMTUlMkMxNSUyQzE1JTJDMTUlMkMxNSUwRCUyMGh0dHBzJTNBJTJGJTJGZW4udWVzcC5uZXQlMkZ3aWtpJTJGU2t5cmltJTNBQXRhciUyQ0F0YXIlMkNOb3JkJTJDTWFsZSUyQ1dhcnJpb3IlMkM1MCUyQihQQy0wLjgpJUMzJTk3MTQuNiUyQzUwJTJDNTAlMkIoUEMtMC44KSVDMyU5NzQuMiUyQyUyMkhlYXZ5JTIwQXJtb3IlMkMlMjBPbmUtaGFuZGVkJTJDJTIwQXJjaGVyeSUyQyUyMEJsb2NrJTIyJTJDS2FydGh3YXN0ZW5TaWx2ZXJGaXNoR3VhcmRzJTJDTm8lMkNBZ2dyZXNzaXZlJTJDTm8lMjBDcmltZSUyQ1NhbnVhcmFjaCUyME1pbmUlMkMyMCUyQzE1JTJDMjAlMkMyNSUyQzIwJTJDIiwibWV0YWRhdGEiOnsiZGlzcGxheV9uYW1lIjoic2t5cmltX2RhdGFfY2xlYW4uY3N2IiwibWltZV90eXBlIjoidGV4dC9wbGFpbiIsImZpbGVfc2l6ZSI6MzE4OTEyLCJjcmVhdGVkX3RpbWUiOiIyMDI1LTAyLTE4VDIwOjU5OjU4IiwidXBkYXRlZF90aW1lIjoiMjAyNS0wMi0xOFQyMDo1OTo1OCIsImxhYmVsIjoiMSJ9fQ%3D%3D)")
    st.write("2. Hroggar: Nord Male Lumberjack with skills in Two-handed, One-handed, and Smithing [2](https://app.textcortex.com/file?id=file_01jmddrh97ffksrmyf8gthbmsy&state=eyJzbmlwcGV0IjoiJTJGd2lraSUyRlNreXJpbSUzQUhyb2dnYXIlMkNIcm9nZ2FyJTJDTm9yZCUyQ01hbGUlMkNMdW1iZXJqYWNrJTJDMTAwJTJDNzAlMkM3MCUyQyUyMlR3by1oYW5kZWQlMkMlMjBPbmUtaGFuZGVkJTJDJTIwU21pdGhpbmclMjIlMkNDcmltZUZhY3Rpb25IamFhbG1hcmNoJTNCJTIwRmF2b3JKb2JzQ2hvcFdvb2RGYWN0aW9uJTNCJTIwSm9iTHVtYmVyamFja0ZhY3Rpb24lM0IlMjBNUzE0QWx2YUFuZEhyb2dnYXIlM0IlMjBUb3duTW9ydGhhbEZhY3Rpb24lMkNObyUyQ0FnZ3Jlc3NpdmUlMkNWaW9sZW5jZSUyMEFnYWluc3QlMjBFbmVtaWVzJTJDJTJDMjAlMkMxNSUyQzIwJTJDMjUlMkMyMCUyQzE1JTJDMjAlMkMxNSUyQzE1JTJDMTUlMkMyMCUyQzE1JTJDMTUlMkMxNSUyQzE1JTJDMTUlMkMxNSUyQzE1JTBEJTIwaHR0cHMlM0ElMkYlMkZlbi51ZXNwLm5ldCUyRndpa2klMkZTa3lyaW0lM0FBZ25pJTJDQWduaSUyQ05vcmQlMkNGZW1hbGUlMkNDaGlsZCUyQzY1JTJDMCUyQzgwJTJDJTIyU21pdGhpbmclMkMlMjBUd28taGFuZGVkJTIyJTJDQ3JpbWVGYWN0aW9uSGphYWxtYXJjaCUzQiUyME1vcnRoYWxGYWxpb25zSG91c2VGYWN0aW9uJTNCJTIwVG93bk1vcnRoYWxGYWN0aW9uJTJDTm8lMkNVbmFnZ3Jlc3NpdmUlMkNObyUyMENyaW1lJTJDJTJDMjAlMkMxNSUyQzIwJTJDMjUlMkMyMCUyQzE1JTJDMjAlMkMxNSUyQzE1JTJDIiwibWV0YWRhdGEiOnsiZGlzcGxheV9uYW1lIjoic2t5cmltX2RhdGFfY2xlYW4uY3N2IiwibWltZV90eXBlIjoidGV4dC9wbGFpbiIsImZpbGVfc2l6ZSI6MzE4OTEyLCJjcmVhdGVkX3RpbWUiOiIyMDI1LTAyLTE4VDIwOjU5OjU4IiwidXBkYXRlZF90aW1lIjoiMjAyNS0wMi0xOFQyMDo1OTo1OCIsImxhYmVsIjoiMiJ9fQ%3D%3D)")
    st.write("3. Rakel: Nord Female Werewolf with skills in One-handed, Sneak, Archery, and Block [3](https://app.textcortex.com/file?id=file_01jmddrh97ffksrmyf8gthbmsy&state=eyJzbmlwcGV0IjoiJTJGd2lraSUyRlNreXJpbSUzQVJha2VsJTJDUmFrZWwlMkNOb3JkJTJDRmVtYWxlJTJDV2VyZXdvbGYlMkMxNDAtMzQwJTJDNTAlMkM5NS0xOTUlMkMlMjJPbmUtaGFuZGVkJTJDJTIwU25lYWslMkMlMjBBcmNoZXJ5JTJDJTIwQmxvY2slMjIlMkNETEMyZHVuRnJvc3Rtb29uV2VyZXdvbHZlc0ZhY3Rpb24lMkNObyUyQ0FnZ3Jlc3NpdmUlMkNObyUyMENyaW1lJTJDRnJvc3Rtb29uJTIwQ3JhZyUyQzIwJTJDMTUlMkMyMCUyQzI1JTJDMjAlMkMxNSUyQzIwJTJDMTUlMkMxNSUyQzE1JTJDMjAlMkMxNSUyQzE1JTJDMTUlMkMxNSUyQzE1JTJDMTUlMkMxNSUwRCUyMGh0dHBzJTNBJTJGJTJGZW4udWVzcC5uZXQlMkZ3aWtpJTJGU2t5cmltJTNBU2FkZW4lMkNTYWRlbiUyQ0RhcmslMjBFbGYlMkNNYWxlJTJDQmFuZGl0JTIwV2l6YXJkJTJDMCUyMChEZWFkKSUyQzEwMCUyQyUyQ0Rlc3RydWN0aW9uJTJDQmFuZGl0RmFjdGlvbiUzQiUyMERMQzJCYW5kaXREaWFsb2d1ZUZhY3Rpb24lMkNObyUyQ1ZlcnklMjBBZ2dyZXNzaXZlJTJDTm8lMjBDcmltZSUyQ0hvcmtlciUyMElzbGFuZCUyQzI2JTJDMjQlMkMyOCUyQzI0JTJDMzQlMkMzMiUyQzMzJTJDMzUlMkMzNiUyQzM4JTJDNDAlMkM0MSUyQzQzJTJDNDQlMkM0NiUyQzQ3JTJDNDklMkM1MCUwRCUyMGh0dHBzJTNBJTJGJTJGZW4uIiwibWV0YWRhdGEiOnsiZGlzcGxheV9uYW1lIjoic2t5cmltX2RhdGFfY2xlYW4uY3N2IiwibWltZV90eXBlIjoidGV4dC9wbGFpbiIsImZpbGVfc2l6ZSI6MzE4OTEyLCJjcmVhdGVkX3RpbWUiOiIyMDI1LTAyLTE4VDIwOjU5OjU4IiwidXBkYXRlZF90aW1lIjoiMjAyNS0wMi0xOFQyMDo1OTo1OCIsImxhYmVsIjoiMyJ9fQ%3D%3D)")

st.sidebar.header("About")
st.sidebar.info(
    "This is a Retrieval-Augmented Generation (RAG) system for Skyrim character information. "
    "It uses a local vector database to find relevant character information and generates "
    "responses using a local language model through LMStudio."
)

